DELETE http://localhost:3001/api/persons/65eed5a42c97490b9b9ad86f

###
POST   http://localhost:3001/api/persons
content-type: application/json

{
    "name": "mefff",
    "number": "10-23-455678"
}

###
GET   http://localhost:3001/api/persons

###
GET   http://localhost:3001/info

###
GET   http://localhost:3001/api/persons/65eecf98b70a71eec018c253
###
POST   http://localhost:3001/api/persons
content-type: application/json

{
   
}

###
POST   http://localhost:3001/api/persons
content-type: application/json

{
    "number": "+905375452087"
}

